### ISSUE TITLE
Check issues

### ISSUE THREAD

**Issue by jobayed80** [jobayed80/Testing-Lab-Reports#4]
Need to find variable bug @Ahsan30-bit

**Comment by Ahsan30-bit** [comment]
![278658846_292068483108683_4295698472401510454_n](https://user-images.githubusercontent.com/102744551/164310985-3356935e-379c-45a9-a108-1818859d1a3c.png)
yes , i check it

**Comment by jobayed80** [comment]
Thank you @Ahsan30-bit

**Comment by jobayed80** [comment]
![image](https://user-images.githubusercontent.com/58429687/164978945-ee58a685-87fe-4160-9e55-e62c2fe77d27.png)
@omarfaruqeanik  please check.

**Comment by omarfaruqeanik** [comment]
@jobayed80 yes i solve this problem

**Comment by jobayed80** [comment]
@omarfaruqeanik thank you.
